name: Meson Build
description: Builds Rofi using Meson

inputs:
  cc:
    description: Compiler to use
    required: true

runs:
  using: composite
  steps:
    - id: pip
      run: pip install meson ninja
      shell: bash
    - id: setup
      run: meson setup builddir -Dwayland=enabled
      shell: bash
      env:
        CC: ${{ inputs.cc }}
    - id: build
      run: ninja -C builddir
      shell: bash
    - id: test
      run: ninja -C builddir test
      shell: bash
    - id: dist
      run: meson dist -C builddir --include-subprojects
      shell: bash
    - id: upload
      uses: actions/upload-artifact@v2
      with:
        name: tarballs
        path: |
          builddir/meson-dist/*.tar.xz
    # - id: doxy
    #   run: ninja -C builddir doc/html 2>&1 > doxygen.log
    #   shell: bash
    # - id: doxycheck
    #   uses: ./.github/actions/doxycheck
    #   with:
    #     logfile: doxygen.log
